FIRMWARE_VERSION=v1.0.3

BUILD_PATH=../build/salus/zephyr/
BUILD_FIMRWARE_PATH=$BUILD_PATH/merged.hex
OTA_FIRMWARE_PATH=$BUILD_PATH/dfu_application.zip

FINAL_FIMRWARE_PATH=$FIRMWARE_VERSION/salus_firmware_$FIRMWARE_VERSION.hex
FINAL_OTA_FIRMWARE_PATH=$FIRMWARE_VERSION/salus_dfu_application_$FIRMWARE_VERSION.zip

rm -R $FIRMWARE_VERSION
mkdir $FIRMWARE_VERSION

cp $BUILD_FIMRWARE_PATH $FINAL_FIMRWARE_PATH
cp $OTA_FIRMWARE_PATH $FINAL_OTA_FIRMWARE_PATH